source :gemcutter
gem "rack"
gem "rack-flash"
gem "sinatra"
gem "data_mapper"
gem "dm-sqlite-adapter"
gem "dm-postgres-adapter"
gem "haml"
gem "json"
gem "pony"
gem "base32", :git => "git://github.com/levinalex/base32.git"
